version: '3'
services:
    redis:
        container_name: redis
        image: redis:7.0.4-alpine
        restart: always
    be:
        container_name: backend
        depends_on:
            - redis
        build:
            dockerfile: Dockerfile
        ports:
            - '5001:${PORT}'
        environment:
            - ORIGIN=${ORIGIN}
            - HOST=${HOST}
            - PORT=${PORT}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - MAILER_USER=${MAILER_USER}
            - MAILER_PASSWORD=${MAILER_PASSWORD}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - ENV=PROD
            - SIGN_ACCESS_TOKEN_PRIVATE=${SIGN_ACCESS_TOKEN_PRIVATE}
            - SIGN_ACCESS_TOKEN_PUBLIC=${SIGN_ACCESS_TOKEN_PUBLIC}
            - SIGN_REFRESH_TOKEN_PRIVATE=${SIGN_REFRESH_TOKEN_PRIVATE}
            - SIGN_REFRESH_TOKEN_PUBLIC=${SIGN_REFRESH_TOKEN_PUBLIC}
